stages:
- test
- name: deploy
  if: (tag =~ ^v) AND (branch = master)

git:
  depth: 1
  submodules: false

language: python
python:
  - 3.7

jobs:
  include:
  - stage: test
    name: flake8
    env:
      - FLAKE8_IGNORE="E302,E305,E501,E741"
      - FLAKE8_EXCLUDE="odepy/__init__.py,drawstuffpy/__init__.py,test/conftest.py"
    install:
      - python3 -m pip install --upgrade flake8
    script:
      - python3 -m flake8 --ignore "${FLAKE8_IGNORE}" --exclude "${FLAKE8_EXCLUDE}" odepy/ drawstuffpy/ test/
  - stage: test
    name: pytest3
    install:
      - sudo apt update
      - sudo apt install -y libode-dev
      - python3 -m pip install --upgrade pytest
    script:
      - python3 -m pytest -v -s test/*
  - stage: test
    name: pytest2
    python:
      - 2.7
    install:
      - sudo apt update
      - sudo apt install -y libode-dev
      - python2 -m pip install --upgrade pytest
    script:
      - python2 -m pytest -v -s test/*
  - stage: deploy
    name: pypi
    env:
      - PYPI_URL="https://upload.pypi.org/legacy/"
      - PYPI_USER="__token__"
      - secure: iOU36VMTjtDkNoaaqDrBHoUxMBfdP1KtWzjwG9LfeQiqEfFO/tVA95RlGoWcvhgBCSX/LFN4nbzk0ZaWpWFzX7DPGCi87WKUC/ymSxxAwfsnkELAfCdHtjLFsN4DqHM2eu5VOdHL6+qxgImQ0mnTOAHAfN3FumfFzqJTv89ZL+vaD8yqjAAt0RRnLtAsDMyokyDW+nLFKAWFbwiqeW3sKqUfHm0hyRGM0yxX7SfOh1vI1MkGr6wWj6I5siPovIqu5OvqyeZQ8IlRVqrbPcD+Al83lmHCFcWWRiksk7tlJ7NV8j9qUIBsxouqRdsEkoPsgGsCfEEsxBwYrybkS19/Gfg3HnU4KljcFKrEE3EldJNEW3xgrmRr/SoCoSl7wbV4BRiZzgR7XbCJYOZZkjP0r+6z/3W++NIRVqqhS1VJVkjJ3e2X8vNTA5fpWJ27VmOaZrCO416a76gvfU+tsXjFo3KwJvnOY0DxnNeI10KRk+90mhW7SfUlsVdof3wQlh/UHaw3FljWBO1MXoIh45wqHX9jTe8kqwKWoEmjgjqp6J1nlaUL7nesVRjxAHxWjXsDWZYW+ge05qs48KS7yPBIEcc8F7EBeEZs3D1kUBDkbrH2bdTfPVp/r2wqLOMLLBFtp3YLB8ZrrQl9yDbopbcAqKYdm92SghfHAa3trgh4/ZE=
    install:
      - python3 -m pip install --upgrade setuptools wheel twine
    script:
      - python3 setup.py sdist bdist_wheel
      - python3 -m twine upload --repository-url "${PYPI_URL}" -u "${PYPI_USER}" -p "${PYPI_PASSWORD}" dist/*
