stages:
  - test
  - name: deploy
    if: branch = master

language: python
python:
  - 3.7

jobs:
  include:
    - stage: test
      name: flake8
      env:
        - FLAKE8_IGNORE="E302,E305,E501"
        - FLAKE8_EXCLUDE="pyode/__init__.py"
      install:
        - python3 -m pip install flake8
      script:
        - python3 -m flake8 --ignore "${FLAKE8_IGNORE}" --exclude "${FLAKE8_EXCLUDE}" pyode/
    - stage: test
      name: pytest
      install:
        - sudo apt update
        - sudo apt install -y libode-dev
      script:
        - python3 -m pytest test/*
    - stage: deploy
      name: pypi
      script:
        - echo ok
